repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: ^backend
      - id: end-of-file-fixer
        files: ^backend

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        name: ruff
        files: ^backend
        args:
          - "--config=backend/pyproject.toml"
          - "--fix"

      - id: ruff-format
        name: ruff format
        files: ^backend
        args: ["--config=backend/pyproject.toml"]
