services:
  app:
    build:
      context: ./backend
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - BROKER_URL=redis://redis:6379/0
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
    depends_on:
      - db
      - redis
      - mailhog

  celery_worker:
    build: ./backend
    command: celery -A app worker -l info
    volumes:
      - ./backend:/app
    environment:
      - BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - mailhog

  celery_beat:
    build: ./backend
    command: celery -A app beat -l info
    volumes:
      - ./backend:/app
    environment:
      - BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  db:
    image: postgres:15.5-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  dev-db-data:
