# Generated by Django 5.2 on 2026-03-04 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='capacity_must_be_positive', violation_error_message='Capacity must be greater than zero.')],
            },
        ),
    ]
