# Generated by Django 5.2 on 2026-03-05 16:11

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_btree_gist_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled')], default='active')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.room')),
                ('users', models.ManyToManyField(related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.Func(models.F('start_datetime'), models.F('end_datetime'), function='tstzrange'), '&&'), ('room', '=')], name='prevent_room_overlap')],
            },
        ),
    ]
