# Generated by Django 5.2 on 2026-03-06 02:21

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_UPDATED', 'Booking Updated'), ('BOOKING_CANCELED', 'Booking Canceled')], max_length=50)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retries', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterConstraint(
            model_name='reservation',
            name='prevent_room_overlap',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.Func(models.F('start_datetime'), models.F('end_datetime'), function='tstzrange'), '&&'), ('room', '=')], name='prevent_room_overlap', violation_error_message='Already have an reservation for that room between these time.'),
        ),
    ]
